string = input("Entrer la chaine de caractere: ")
char_to_replace = input("entrer le caractere a remplacer: ")
new_char = input("entrer le nouveau caractere: ")
new_string = string.replace(char_to_replace, new_char)
print(new_string)